### ISSUE TITLE
Update Gatsby installation docs

### ISSUE THREAD

**Issue by kaushalyap** [tailwindlabs/tailwindcss.com#921]
Current [Gatsby Tailwindcss install instructions](https://tailwindcss.com/docs/guides/gatsby) does not work getting following after `gatsby develop`

```
Generating development JavaScript bundle failed

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin tailwindcss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (...node_modules/postcss/lib/processor.es6:117:15)
    at new Processor (...node_modules/postcss/lib/processor.es6:38:25)
    at postcss (...node_modules/postcss/lib/postcss.es6:34:10)
    at Object.loader (...node_modules/postcss-loader/dist/index.js:95:20)

File: .cache/blank.css


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin tailwindcss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (...node_modules/postcss/lib/processor.es6:117:15)
    at new Processor (...node_modules/postcss/lib/processor.es6:38:25)
    at postcss (...node_modules/postcss/lib/postcss.es6:34:10)
    at Object.loader (...node_modules/postcss-loader/dist/index.js:95:20)

File: src/styles/global.css

failed Building development bundle - 5.472s
ERROR in ./.cache/blank.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin tailwindcss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (...node_modules/postcss/lib/processor.es6:117:15)
    at new Processor (...node_modules/postcss/lib/processor.es6:38:25)
    at postcss (...node_modules/postcss/lib/postcss.es6:34:10)
    at Object.loader (...node_modules/postcss-loader/dist/index.js:95:20)
    at processResult (...node_modules/webpack/lib/NormalModule.js:703:19)
    at ...node_modules/webpack/lib/NormalModule.js:809:5
    at ...node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at ...node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (...node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (...node_modules/postcss-loader/dist/index.js:104:7)
 @ ./.cache/app.js 25:0-21

ERROR in ./src/styles/global.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin tailwindcss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (...node_modules/postcss/lib/processor.es6:117:15)
    at new Processor (...node_modules/postcss/lib/processor.es6:38:25)
    at postcss (...node_modules/postcss/lib/postcss.es6:34:10)
    at Object.loader (...node_modules/postcss-loader/dist/index.js:95:20)
    at processResult (...node_modules/webpack/lib/NormalModule.js:703:19)
    at ...node_modules/webpack/lib/NormalModule.js:809:5
    at ...node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at ...node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (...node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (...node_modules/postcss-loader/dist/index.js:104:7)
 @ ./gatsby-browser.js 4:0-33
 @ ./.cache/api-runner-browser-plugins.js 35:10-41
 @ ./.cache/api-runner-browser.js 4:14-53
 @ ./.cache/app.js 12:0-65 29:87-33:1 37:20-29 50:0-14 116:17-26 150:6-15 29:0-33:2

2 ERRORS in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 4 errors
success Writing page-data.json files to public directory - 0.163s - 3/9 55.38/s
```

what work for gatsby too is CRA install instructions. AFIK This is may be because `gatsby-cli` is fork of CRA, so issues in the CRA exists in `gatsby-cli` too.

**Comment by kaushalyap** [comment]
I tried to reproduce this on new gatsby project with instructions given in the tailwindcss docs, everything worked fine. even though the instruction is to install all as deps resulting package.json dependency section looked like below

```
 "dependencies": {
    "gatsby": "^3.11.1",
    "gatsby-plugin-postcss": "^4.12.0",
    "postcss": "^8.3.6",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
  "devDependencies": {
    "autoprefixer": "^10.3.2",
    "tailwindcss": "^2.2.7"
  }
```

by changing package.json of my previous project similar to above I was able to get it work.

Amazing thing is `gatsby-plugin-postcss` was automatically added to the `gatsby-config.js` in the new project.

I think this is some kind of glitch. so I am closing this now.
